---
title: "Paper 1"
author: "Marion Nyberg"
date: "27/04/2022"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(janitor)
library(plotly)
library(plyr)
library(dplyr)
library(knitr)
library(tidyverse)
#library(devtools)
library(openair)
library(tidyr)
library(naniar)
library(forecast)
library(kableExtra)
library(htmltools)
library(ggpubr)
library(rstatix)
library(broom)
library(gtable)
library(gridExtra)
library(cowplot)
library(viridis)
library(zoo)

rm(list = ls())
#wd <- ("R:/SET/PlantSci/Shared Work Spaces/Ecology/Flux/SP_data")
#setwd(wd)
#knitr::opts_knit$set(root.dir = wd)
```

Below are conversion factors and functions used in the markdown file:

```{r functions and conversions}
d.avg <- 1800 * 48 #60 secs * 60 mins * 24 hours (# of secs in day)
co2_conv <- 12.01/(10^6) 

tidy.csv <- function(x){
  input <- x[-c(1,2),] %>%
    row_to_names(., 1)
}  

gofC.f <- function(x){ # function to convert to mean 30 minute to g of C
  (x*d.avg)*co2_conv
}

gtomg.f <- function(x){ # function to convert from g to mg
  x*1000
}
```

```{r read data and some data class cleaning, include=FALSE}
input <- fread("R:/SET/PlantSci/Shared Work Spaces/Ecology/Flux/SP_data/PFP/L6/SilverPlains_L6.csv", header = FALSE, na.strings = "-9999") 
input <- tidy.csv(input)

input <- input %>% select(xlDateTime, Fe, Fg_Av, Fh, Fld, Flu, Fn, Fsu, Fsd, Precip, RH, Sws, Ta, Ts, VPD, Wd_SONIC_Av, Ws_SONIC_Av,ER_LT_all, GPP_LT,GPP_SOLO, NEE_LT, ET_EF ) # select met variables (add more as needed)
colnames(input) <- c('Timestamp', 'LE', 'G', 'H', 'LWin', 'LWout', 'NETRAD', 'SWout', 'SWin', 'Precip', 'RH', 'SWC', 'Ta', 'Ts', 'VPD', 'WD', 'WS', 'ER_LT', 'GPP_LT', 'GPP_SOLO', 'NEE_LT', 'ET')

input$Timestamp <- as.POSIXct(input$Timestamp, format= "%d/%m/%Y %H:%M") # change from character to POSIXct
input[,2:21] <- as.data.frame(sapply(input[,2:21], as.numeric)) # convert data frame from character to numeric

input$jday <-yday(input$Timestamp) # add jday
input$Year <- year(input$Timestamp) # extract year
input$Year <- as.factor(input$Year) # convert year from integer to factor
input$month <- month(as.POSIXct(input$Timestamp)) # extract month
input$month <- as.factor(input$month)
```

```{r weird stuff in data filtered out}
input$SWin <- ifelse(input$SWin < 0, NA, input$SWin)
```

```{r create daily mean dataframe, include=FALSE}
# add variables to this daily df as needed
input.daily <- input %>%
  drop_na(Timestamp) %>% # some NAs in the Timestamp for some reason. Need to look into
  ddply(c("Year", "jday", "month"), summarise,
        Precip = sum(Precip, na.rm = TRUE),
        SWin = sum(SWin),
        Ta.mean = mean(Ta, na.rm = TRUE),
        Ta.max = max(Ta, na.rm = TRUE),
        Ta.min = min(Ta, na.rm = TRUE),
        Ts.mean = mean(Ts, na.rm = TRUE),
        Ts.max = max(Ts, na.rm = TRUE),
        Ts.min = min(Ts, na.rm = TRUE),
        SWC = mean(SWC, na.rm = TRUE),
        RH = mean(RH, na.rm = TRUE),
        VPD = mean(VPD, na.rm = TRUE),
        ET = mean(ET, na.rm = TRUE),
        NEE_LT = mean(NEE_LT, na.rm = TRUE), #daily average umol m-2 s-1
        ER_LT = mean(ER_LT, na.rm = TRUE),
        GPP_LT = mean(GPP_LT, na.rm = TRUE)) %>%
  mutate(NEE_LT.gC = gofC.f(NEE_LT),  #converts to daily total NEE in g C CO2
         ER_LT.gC = gofC.f(ER_LT),
         GPP_LT.gC = gofC.f(GPP_LT))

input.daily$month <- as.numeric(input.daily$month) 
input.daily$month.name <- month.abb[input.daily$month]
input.daily$date <- as.Date(with(input.daily,paste(Year,month,jday,sep="-")),"%Y-%m-%j")


```

```{r}
input.daily$dayssinceJun1 <- ""

Grow19.20 <- input.daily[1:164,]
Grow19.20$dayssinceJun1 <- 202:365
Grow19.20$GSYear <- "19/20"

Grow20.21 <- input.daily[165:529,]
Grow20.21$dayssinceJun1 <- 1:365
Grow20.21$GSYear <- "20/21"

Grow21.22 <- input.daily[530:907,]
Grow21.22$dayssinceJun1 <-1:378
Grow21.22$GSYear <- "21/22"

input.rearranged <- rbind(Grow19.20,Grow20.21, Grow21.22)
input.rearranged$monthyear <- as.yearmon(paste(input.rearranged$month, input.rearranged$Year), "%m %Y")



start.time <- as.Date("2020-06-01", "%m-%d")
end.time <- as.Date("2022-05-31", "%m-%d")
start.end <- c(start.time, end.time)
```

```{r}
input.rearranged$season <- "" # add season variable

# define seasons
winter <- (input.rearranged$month.name == "Jun" | input.rearranged$month.name == "Jul" | input.rearranged$month.name == "Aug")
spring <- (input.rearranged$month.name == "Sep" | input.rearranged$month.name == "Oct" | input.rearranged$month.name == "Nov")
summer <- (input.rearranged$month.name == "Dec" | input.rearranged$month.name == "Jan" | input.rearranged$month.name == "Feb")
autumn <- (input.rearranged$month.name == "Mar" | input.rearranged$month.name == "Apr" | input.rearranged$month.name == "May")

input.rearranged$season[winter] <- "Winter"
input.rearranged$season[spring] <- "Spring"
input.rearranged$season[summer] <- "Summer"
#input.rearranged$season[latesummer] <- "LateSummer"
input.rearranged$season[autumn] <- "Autumn"

input.rearranged$season <- factor(input.rearranged$season , levels=c('Summer', 'Autumn', 'Winter', 'Spring'))
```

## Results {.tabset}

### Precipitation

```{r Precipitation, echo=FALSE, message = FALSE, fig.width = 8, fig.height = 4}
#below is precip data from liaweenee - it only goes up to Jan 2022 right now
rainfall_L <- read.csv("R:/SET/PlantSci/Shared Work Spaces/Ecology/Peoples files/Marion Nyberg/PhD/Rainfall/rainfall.csv")
rainfall_L <- rainfall_L[-4]
colnames(rainfall_L)[4] <- "Precip"
rainfall_L$Year <- as.factor(rainfall_L$Year)
rainfall_L <- rainfall_L %>% filter(Year == 2019)
colnames(rainfall_L)[1] <- "jday"
colnames(rainfall_L)[3] <- "month"
rainfall_L$Site <- "L"
rainfall_L <- rainfall_L %>% filter(month >= 6)
rainfall_L$month <- as.numeric(rainfall_L$month) 
rainfall_L$month.name<- month.abb[rainfall_L$month]
rainfall_L$GSYear <- "19/20"

# define seasons
winter <- (rainfall_L$month.name == "Jun" | rainfall_L$month.name == "Jul" | rainfall_L$month.name == "Aug")
spring <- (rainfall_L$month.name == "Sep" | rainfall_L$month.name == "Oct" | rainfall_L$month.name == "Nov")
summer <- (rainfall_L$month.name == "Dec" | rainfall_L$month.name == "Jan" | rainfall_L$month.name == "Feb")
autumn <- (rainfall_L$month.name == "Mar" | rainfall_L$month.name == "Apr" | rainfall_L$month.name == "May")

rainfall_L$season[winter] <- "Winter"
rainfall_L$season[spring] <- "Spring"
rainfall_L$season[summer] <- "Summer"
rainfall_L$season[autumn] <- "Autumn"

rainfall_L$season <- factor(rainfall_L$season , levels=c('Summer', 'Autumn', 'Winter', 'Spring'))
```

```{r, fig.width=11, fig.height=4}
season.colors <- c("Summer" = "#E69F00", "Autumn" = "#D55E00", "Winter" ="#0072B2", "Spring" = "#CC79A7")


rainfall.SP <- input.rearranged %>% select(Precip, month, GSYear, season, Year, month.name)


rainfall <- rainfall_L %>% select(Precip, month, GSYear, season, Year, month.name) %>% rbind(., rainfall.SP)

rainfall$monthyear <- as.yearmon(paste(rainfall$month, rainfall$Year), "%m %Y")

(rainfall.season <- rainfall %>%  mutate(Precip = replace_na(Precip, 0)) %>%
  ddply(c("GSYear", "season"), summarise,
  seasonal.total = sum(Precip)) %>%
  ggplot(., aes(x = GSYear, y = seasonal.total, group = GSYear, fill = season)) +
       #scale_x_discrete(limits = month.abb) +
  geom_col(aes(fill = season)) +
        scale_fill_manual(values = season.colors)+
  ylab("Seasonal rainfall (mm)")+
  xlab("Growing season year")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14)))

rainfall.season
tiff("rain.tiff", units="in", width=10, height=6,  res=300)
print(rainfall.season)
dev.off()

(rainfall.p <-rainfall %>%  mutate(Precip = replace_na(Precip, 0)) %>%
  ddply(c("monthyear", "Year"), summarise,
  monthly.total = sum(Precip)) %>%
  ggplot(., aes(x = monthyear, y = monthly.total)) +
  geom_col(position = "dodge") +
  scale_x_yearmon(n = 7, expand = c(0,0))+
  ylab("Monthly rainfall (mm)")+
  xlab("Date")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14),
          axis.text.x = element_text( vjust = 0.5)))
rainfall.p
tiff("rainfall.tiff", units="in", width=10, height=6,  res=300)
print(rainfall.p)
dev.off()


rainfall.summary <- rainfall %>%  mutate(Precip = replace_na(Precip, 0)) %>%
  ddply(c("GSYear", "season"), summarise,
  seasonal.total = sum(Precip))
```

### Air and soil temperature

```{r Air temperature, echo=FALSE, message = FALSE, fig.width = 13, fig.height = 3}
(TA <- ggplot(input.rearranged, aes(x = date, y = Ta.mean)) +
   geom_point(size = 0.001)+
   geom_line(size = 0.72)+
        geom_ribbon(aes(ymin=Ta.min, ymax=Ta.max), alpha=.3, linetype=0) +
   
    xlab("Date")+
    ylab("Air temperature (째C)")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14)))

(TS <- ggplot(input.rearranged, aes(x = date, y = Ts.mean)) +
   geom_point(size = 0.001)+
   geom_line(size = 0.72)+
        geom_ribbon(aes(ymin=Ts.min, ymax=Ts.max), alpha=.3, linetype=0) +
    xlab("Date")+
    ylab("Soil temperature (째C)")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14)))

TA
tiff("TA.tiff", units="in", width=10, height=6,  res=300)
print(TA)
dev.off()

TS
tiff("TS.tiff", units="in", width=10, height=6,  res=300)
print(TS)
dev.off()
```

```{r fig.width=7, fig.height=5}
TA.summary <- input.rearranged %>% ddply(c("GSYear", "season"), summarise,
                                       mean.TA = mean(Ta.mean),
                                       mean.TS = mean(Ts.mean))
#ER.summary$month.name <- factor(ER.summary$month.name, levels=c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun"))

TA.summary$season <- factor(TA.summary$season, levels=c("Winter", "Spring", "Summer", "Autumn"))

(TA.sum.p <-TA.summary %>% 
  ggplot(., aes(x = GSYear, y = mean.TA), group = season) +
  geom_col(position = position_dodge2(width = 0.9, preserve = "single"), aes(fill = season)) +
                scale_fill_manual(values = season.colors)+
  ylab("Air temperature (째C)")+
  xlab("Date")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14),
          axis.text.x = element_text( vjust = 0.5)))

TA.sum.p
tiff("TAbar.tiff", units="in", width=10, height=6,  res=300)
print(TA.sum.p)
dev.off()

(TS.sum.p <-TA.summary %>% 
  ggplot(., aes(x = GSYear, y = mean.TS), group = season) +
  geom_col(position = position_dodge2(width = 0.9, preserve = "single"), aes(fill = season)) +
                    scale_fill_manual(values = season.colors)+
  ylab("Soil temperature (째C)")+
  xlab("Date")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14),
          axis.text.x = element_text( vjust = 0.5)))

TS.sum.p
tiff("TSbar.tiff", units="in", width=10, height=6,  res=300)
print(TS.sum.p)
dev.off()


```

### VPD

```{r VPD, echo=FALSE, message = FALSE, fig.width = 9, fig.height = 4}
(VPD.p <- ggplot(input.rearranged, aes(x = dayssinceJun1, y = VPD, group = GSYear)) +
  geom_line(aes(color = GSYear), size = 1)+
    scale_color_manual(values = group.colour) +
 # scale_x_date(date_labels = "%b", date_breaks = "1 month") +
  xlab("Days since June 1st")+
   ylab("VPD (kPa")+
  theme_classic())+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14))

VPD.p
tiff("VPD.tiff", units="in", width=10, height=6,  res=300)
print(VPD.p)
dev.off()

```


### SWC

```{r, echo=FALSE, message = FALSE, fig.width = 7, fig.height = 4}
group.colour <- c("19/20" = "#E69F00", "20/21" = "#009E73", "21/22" ="#D55E00")

input.rearranged$dayssinceJun1 <- as.numeric(input.rearranged$dayssinceJun1)

(SWC.20 <- input.rearranged  %>% filter(GSYear == "19/20" ) %>% ggplot(., aes(dayssinceJun1, SWC), group = GSYear) +
  geom_line(aes(color = GSYear), size = 1)+
   scale_x_continuous(limits = c(1, 365))+
  xlab('Days since June 1st') +
        ylab(bquote('SWC ('~m^3~'/'~m^-3~')'))+

#  ylab('SWC') +
  # scale_x_continuous()+
    scale_color_manual(values=group.colour)+
  theme_classic() + 
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.position = "none"))


SWC.20
tiff("SWC20.tiff", units="in", width=10, height=6,  res=300)
print(SWC.20)
dev.off()
```





```{r add seasons, include=FALSE}
#rainfall$season <- "" # add season variable

# define seasons
#winter <- (rainfall$month == "Jun" | rainfall$month == "Jul" | rainfall$month == "Aug")
#spring <- (rainfall$month == "Sep" | rainfall$month == "Oct" | rainfall$month == "Nov")
#summer <- (rainfall$month == "Dec" | rainfall$month == "Jan" | rainfall$month == "Feb")
#autumn <- (rainfall$month == "Mar" | rainfall$month == "Apr" | rainfall$month == "May")

#rainfall$season[winter] <- "Winter"
#rainfall$season[spring] <- "Spring"
#rainfall$season[summer] <- "Summer"
#rainfall$season[earlysummer] <- "EarlySummer"
#rainfall$season[latesummer] <- "LateSummer"
#rainfall$season[autumn] <- "Autumn"

#rainfall$season <- factor(rainfall$season , levels=c('Summer', 'Autumn', 'Winter', 'Spring'))
```


```{r seasonal NEE}
NEE.summary <- input.rearranged %>% ddply(c("GSYear", "month.name"), summarise,
                                       monthly.sum = sum(NEE_LT.gC))
NEE.summary$month.name <- factor(NEE.summary$month.name, levels=c("Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May"))


(NEE.bar <- NEE.summary  %>%
  ggplot(., aes(x = month.name, y = monthly.sum, group = GSYear, fill = GSYear)) +
  geom_col(position = position_dodge2(width = 0.9, preserve = "single"), aes(fill = GSYear)) + 
    scale_fill_manual(values = group.colour)+
         #scale_x_discrete(limits = start.end)+
    ylab(bquote('Monthly NEE (g C ' ~m^-2~')'))+
  xlab("Month")+
  theme_classic())+
   theme(axis.title = element_text(size = 15),
          axis.text = element_text(size = 14),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14))

NEE.bar
tiff("NEEbar.tiff", units="in", width=10, height=6,  res=300)
print(NEE.bar)
dev.off()
```

```{r}
GPP.summary <- input.rearranged %>% ddply(c("GSYear", "season"), summarise,
                                       monthly.sum = sum(GPP_LT.gC))

GPP.summary <- input.rearranged %>% ddply(c("GSYear"), summarise,
                                       monthly.sum = sum(GPP_LT.gC))
#GPP.summary$month.name <- factor(GPP.summary$month.name, levels=c("Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", #"Apr", "May"))
GPP.summary$season <- factor(GPP.summary$season, levels=c("Winter", "Spring", "Summer", "Autumn"))

(GPP.bar <- GPP.summary  %>%
  ggplot(., aes(x = season, y = monthly.sum, group = GSYear, fill = GSYear)) +
  geom_col(position = "dodge", aes(fill = GSYear)) + 
         #scale_x_discrete(limits = start.end)+
  ylab("Monthly GPP")+
  xlab("month")+
  theme_classic())

GPP.bar
tiff("GPPbar.tiff", units="in", width=10, height=6,  res=300)
print(GPP.bar)
dev.off()
```

```{r}
ER.summary <- input.rearranged %>% ddply(c("GSYear", "season"), summarise,
                                       monthly.sum = sum(ER_LT.gC))

#ER.summary <- input.rearranged %>% ddply(c("GSYear"), summarise,
 #                                      monthly.sum = sum(ER_LT.gC))

#ER.summary$month.name <- factor(ER.summary$month.name, levels=c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun"))

ER.summary$season <- factor(ER.summary$season, levels=c("Winter", "Spring", "Summer", "Autumn"))


(ER.bar <- ER.summary  %>%
  ggplot(., aes(x = season, y = monthly.sum, group = GSYear, fill = GSYear)) +
  geom_col(position = "dodge", aes(fill = GSYear)) + 
         #scale_x_discrete(limits = start.end)+
  ylab("Monthly ER")+
  xlab("month")+
  theme_classic())

ER.bar
tiff("ERbar.tiff", units="in", width=10, height=6,  res=300)
print(ER.bar)
dev.off()
```



```{r cumulative fluxes, fig.width = 7, fig.height = 4}
cum.co2fluxes <- input.rearranged %>% #input.daily %>%
  select(NEE_LT.gC, GPP_LT.gC, ER_LT.gC, dayssinceJun1, GSYear, season) %>% 
  group_by(GSYear, season) %>% 
  mutate(NEEcum = cumsum(NEE_LT.gC),
         GPPcum = cumsum(GPP_LT.gC),
         ERcum = cumsum(ER_LT.gC))

cum.co2fluxes$season <- factor(cum.co2fluxes$season, levels=c("Winter", "Spring", "Summer", "Autumn"))


(NEEcum.p <-cum.co2fluxes %>% 
  ggplot(., aes(dayssinceJun1, NEEcum, group = GSYear, color = GSYear)) +
  geom_line(size = 1, aes(color = GSYear))+
    scale_color_manual(values = group.colour)+
       scale_x_continuous(limits = c(1, 365))+
  ylab(bquote('Cumulative NEE (g C ' ~m^-2~')'))+
  xlab("Days since June 1st")+
  theme_classic()+ 
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13)))


NEEcum.p
tiff("NEEcum.tiff", units="in", width=10, height=6,  res=300)
print(NEEcum.p)
dev.off()

(GPPcum.p <-cum.co2fluxes %>% 
  ggplot(., aes(dayssinceJun1, GPPcum, color = GSYear)) +
  geom_line(size = 1)+
        scale_color_manual(values = group.colour)+
       scale_x_continuous(limits = c(1, 365))+
  ylab(bquote('Cumulative GPP (g C ' ~m^-2~')'))+
  xlab("Days since June 1st")+
  theme_classic()+ 
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13)))

GPPcum.p
tiff("GPPcum.tiff", units="in", width=10, height=6,  res=300)
print(GPPcum.p)
dev.off()

(GPPtime.p <-input.rearranged %>% filter(GPP_LT.gC>0) %>%
  ggplot(., aes(dayssinceJun1, GPP_LT.gC, color = GSYear)) +
  geom_line(size = 1)+
        scale_color_manual(values = group.colour)+
       scale_x_continuous(limits = c(1, 365))+

  ylab(bquote(' GPP (g C ' ~m^-2~')'))+
  xlab("Days since June 1st")+
  theme_classic()+ 
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13)))

GPPtime.p
tiff("GPPtime.tiff", units="in", width=10, height=6,  res=300)
print(GPPtime.p)
dev.off()

(ERcum.p <-cum.co2fluxes %>% 
  ggplot(., aes(dayssinceJun1, ERcum, color = GSYear)) +
  geom_line(size =1)+
        scale_color_manual(values = group.colour)+
       scale_x_continuous(limits = c(1, 365))+

  ylab(bquote('Cumulative ER (g C' ~m^-2~')'))+
  xlab("Days since June 1st")+
  theme_classic()+ 
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13)))

ERcum.p
tiff("ERcum.tiff", units="in", width=10, height=6,  res=300)
print(ERcum.p)
dev.off()

(ERtime.p <-input.rearranged %>% 
  ggplot(., aes(dayssinceJun1, ER_LT.gC, color = GSYear)) +
  geom_line(size = 1)+
        scale_color_manual(values = group.colour)+
       scale_x_continuous(limits = c(1, 365))+

  ylab(bquote('ER (g C ' ~m^-2~')'))+
  xlab("Days since June 1st")+
  theme_classic()+ 
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13)))

ERtime.p
tiff("ERtime.tiff", units="in", width=10, height=6,  res=300)
print(ERtime.p)
dev.off()


Fig2 <- plot_grid(NEE.bar, NEEcum.p,
             GPPcum.p, ERcum.p, ncol = 2, rel_heights = c(0.5, 0.5, 0.5, 0.5))


Fig2
tiff("Fig2.tiff", units="in", width=10, height=6,  res=300)
print(Fig2)
dev.off()

```




```{r}
GPP.summary<- cum.co2fluxes %>% select(GPP_LT.gC,dayssinceJun1, GSYear, season) %>% 
  group_by(GSYear, season) %>% 
   ddply(c("GSYear", "season"), summarise,
  seasonal.total = cumsum(GPP_LT.gC))

cum.co2fluxes$season <- factor(cum.co2fluxes$season, levels=c("Autumn", "Summer", "Spring", "Winter"))


(GPP.bar.s <- cum.co2fluxes  %>%
  ggplot(., aes(x = GSYear, y = GPP_LT.gC, group = season, fill = season)) +
  geom_col(aes(fill = season)) + 
         #scale_x_discrete(limits = start.end)+
  xlab("month")+
         ylab(bquote('Total seasonal GPP (g C ' ~m^-2~')'))+
    scale_fill_manual(values = season.colors)+
  theme_classic()) +
  theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14))


GPP.bar.s
tiff("GPPbar.tiff", units="in", width=10, height=6,  res=300)
print(GPP.bar.s)
dev.off()

GPP.summary <- cum.co2fluxes %>% ddply(c("GSYear", "season"), summarise,
                                       monthly.sum = sum(GPP_LT.gC))


(ER.bar.s <- cum.co2fluxes  %>%
  ggplot(., aes(x = GSYear, y = ER_LT.gC, group = season, fill = season)) +
  geom_col(aes(fill = season)) + 
         #scale_x_discrete(limits = start.end)+
  xlab("month")+
         ylab(bquote('Total seasonal ER (g C ' ~m^-2~')'))+
    scale_fill_manual(values = season.colors)+
  theme_classic()) +
  theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14))


ER.bar.s
tiff("ERbar.tiff", units="in", width=10, height=6,  res=300)
print(ER.bar.s)
dev.off()

ER.summary <- cum.co2fluxes %>% ddply(c("GSYear", "season"), summarise,
                                       monthly.sum = sum(ER_LT.gC))

```
```{r}

rainfall$season <- factor(rainfall$season, levels=c("Winter", "Spring", "Summer", "Autumn"))

(rain <- rainfall %>%  mutate(Precip = replace_na(Precip, 0)) %>%
  ddply(c("GSYear", "season"), summarise,
  seasonal.total = sum(Precip)) %>%
  ggplot(., aes(x = GSYear, y = seasonal.total, group = GSYear, fill = season)) +
       #scale_x_discrete(limits = month.abb) +
  geom_col() + 
  ylab("Seasonal rainfall (mm)")+
  xlab("Growing season year")+
  theme_classic()+
    theme(axis.title = element_text(size = 14),
          axis.text = element_text(size = 13),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14)))
```
